#!/bin/bash

WIKI=/home/git/repos/wiki
PIDFILE=/var/run/markdoc.pid
export PATH=/home/git/bin:$PATH
export MARKDOC=/usr/local/bin/markdoc

test -x $MARKDOC || exit 0

function start_markdoc {
  nohup "/usr/bin/python" "$MARKDOC" -c "$WIKI" serve 1>> "/var/log/markdoc.log" 2>&1 &
  echo $! > "$PIDFILE"
}

function stop_markdoc {
  kill `cat $PIDFILE`
}

case $1 in
  start)
    start_markdoc ;;
  stop)
    stop_markdoc ;;
  restart)
    stop_markdoc
    rm -rf $PIDFILE
    start_markdoc
    ;;
  *)
    echo "usage: markdoc {start|stop}" ;;
esac
exit 0
